# Data directory
data_dir : "${PROJECT_DIR}/examples/"

# Backend API config
backend_api_host : "127.0.0.1"
backend_api_port : 8000

# Frontend config
frontend_host : "0.0.0.0"
frontend_port : 8001

# Auth
auth_username: admin
auth_password: admin # 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918

# Email
smtp_server: smtp.gmail.com
smtp_port: 587
smtp_usetls: true
smtp_username: abc@gmail.com
smtp_password: abc
email_recipients:
  - abc@gmail.com